// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA34mhtpJAoKAmqvxQGZifjcX5Wu4jb2hM',
    appId: '1:882538989529:web:45e832e9c458fc20e97bc8',
    messagingSenderId: '882538989529',
    projectId: 'pharmacy-chain-managemen-ff760',
    authDomain: 'pharmacy-chain-managemen-ff760.firebaseapp.com',
    storageBucket: 'pharmacy-chain-managemen-ff760.firebasestorage.app',
    measurementId: 'G-1KHVTQYDXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZPfLU-LuDBUTxHX2IbyVSUnFMM11B7Q',
    appId: '1:882538989529:android:68cc917347a3ee21e97bc8',
    messagingSenderId: '882538989529',
    projectId: 'pharmacy-chain-managemen-ff760',
    storageBucket: 'pharmacy-chain-managemen-ff760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZNIhH2Vo_Be4YOVNkxykmaPkzqIFEJg4',
    appId: '1:882538989529:ios:0462469d98ccb154e97bc8',
    messagingSenderId: '882538989529',
    projectId: 'pharmacy-chain-managemen-ff760',
    storageBucket: 'pharmacy-chain-managemen-ff760.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyChain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZNIhH2Vo_Be4YOVNkxykmaPkzqIFEJg4',
    appId: '1:882538989529:ios:0462469d98ccb154e97bc8',
    messagingSenderId: '882538989529',
    projectId: 'pharmacy-chain-managemen-ff760',
    storageBucket: 'pharmacy-chain-managemen-ff760.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA34mhtpJAoKAmqvxQGZifjcX5Wu4jb2hM',
    appId: '1:882538989529:web:461792c914696d88e97bc8',
    messagingSenderId: '882538989529',
    projectId: 'pharmacy-chain-managemen-ff760',
    authDomain: 'pharmacy-chain-managemen-ff760.firebaseapp.com',
    storageBucket: 'pharmacy-chain-managemen-ff760.firebasestorage.app',
    measurementId: 'G-VXHHS1XPY0',
  );
}
